### PR TITLE
compare proportion

### PR DESCRIPTION
**Pull request by aw-west-defra**

### CODE REVIEW

**Review by obi-defra — CHANGES_REQUESTED** [review]
Code is all fine. Really nice idea to use t-tests but not sure the result for national parks is right. When I run the notebook I get 1.688e-06, despite the fact that the diff is generally very small. 

I think this is due to large numbers of observations, which tend to produce significant p-values even if the magnitude of difference is small.

I suggest removing the t-test and just plotting the histograms and displaying the describe() output.

**Comment by aw-west-defra** [comment]
Ops, national parks p-value should be 0, which is accepting null.

**Comment by obi-defra** [comment]
Hia, not sure about this. Typically p values <0.05 mean the null hypothesis is rejected.

In this case you have two p-values: 0.66 and 0.00. For one of these tests the null hypothesis should be accepted and rejected for the other, but the doc string says the null is accepted for both.

I think this is due to the large number of observations for the national parks data, which is resulting in two samples of proportions which are significantly different (in the technical sense) while being close in value. Open to other explanations though, I am surprised by the low p-value.

**Review by obi-defra — CHANGES_REQUESTED** [review]
See comment in conversation. Conclusions based on p-values are inconsistent.

**Review by obi-defra — APPROVED** [review]
Made a couple of minor edits and approved.

**Pull request merged**
